FROM node:20-alpine AS builder
WORKDIR /app
COPY ../../backend/package*.json ./
RUN npm ci
COPY ../../backend .
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY ../../backend/package*.json ./
COPY ../../backend/prisma ./prisma
EXPOSE 4000
CMD ["node", "dist/main"]
